package com.moneymanager.entity;

public enum AccountType {
    CASH, BANK, UPI, PAYTM, PHONEPE, GOOGLE_PAY, CREDIT_CARD, DEBIT_CARD,
    WALLET, SIP, MUTUAL_FUND, STOCK_PORTFOLIO, GOLD, CRYPTOCURRENCY, LOAN_ACCOUNT, OTHER
}
